apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  #namespace: school-of-net
  labels:
    app: redis
    role: slave
    tier: backend
spec:
  selector:
    app: redis
    role: slave
    tier: backend
  ports:
  - port: 6379
    targetPort: 6379
