apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  #namespace: teste
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: backend
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
      - name: slave
        image: gcr.io/google_containers/redis:e2e
        resources:
          limits:
            memory: "128Mi"
            cpu: "0.1"
        env:    
        - name: GET_HOST_FROM
          #value: dns
        ports:
        - containerPort: 6379
