apiVersion: v1
kind: Service
metadata:
  name: redis-master
  #namespace: teste
  labels:
    app: redis
    role: master
    tier: backend
spec:
  selector:
    app: redis
    role: master
    tier: backend
  ports:
  - port: 6379
    targetPort: 6379
