apiVersion: v1
kind: Service
metadata:
  name: frontend
  #namespace: test
  labels:
    app: guestbook
    tier: frontend
spec:
  selector:
    app: guestbook
    tier: frontend
  type: LoadBalancer  
  ports:
  - port: 80
  #necessário inserir o IP externo para conexão do frontend.
  #esse ip normalmente está em um cloud 
   
